---
- name: Update and Restart Linux Red Hat Servers
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    update_packages: true

  tasks:
    - name: Display Distribution
      debug:
        msg: "Server {{ inventory_hostname }} is: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}."

    - name: Check for available updates (dry-run)
      package:
        name: "*"
        state: latest
      check_mode: yes
      register: check_updates_result
      failed_when: false # Don't fail if no updates are available

    - name: Set fact for available updates
      set_fact:
        updates_available: "{{ check_updates_result.changed }}"

    - name: Count and list available updates
      debug:
        msg:
          - "Updates available: {{ updates_available }}"
          - "Packages to be updated:"
          - "{{ check_updates_result.updates | default([]) }}"
      when: updates_available

    - name: Install updates
      package:
        name: "*"
        state: latest
      register: install_updates_result
      when: updates_available

    - name: Check if a restart is needed
      command: needs-restarting -r
      register: rpm_restart_needed
      failed_when: rpm_restart_needed.rc != 0

    - name: Reboot the server if required
      reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 10
      ignore_errors: true
      register: reboot_result
      when: rpm_restart_needed is changed

    - name: Log OS Distribution and Version
      gather_facts: # Re-gather facts

    - name: Display Distribution Post Patching
      debug:
        msg: "Server {{ inventory_hostname }} is: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}."

