---
- name: Update and Restart Linux Servers
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    report_file: "/tmp/patching_report_{{ ansible_date_time.iso8601_basic_short }}.html"
    email_recipient: ""  # Change this!
    email_subject: "Patching Report - {{ ansible_hostname }} - {{ ansible_date_time.iso8601_basic_short }}"
    email_from: "" # Change this!
    email_smtp_server: "" # Change this!
    email_smtp_port: "" # or 465, 587 depending on your SMTP server
    email_smtp_user: "" # Optional, if your SMTP requires auth
    email_smtp_password: "" # Optional, if your SMTP requires auth

  tasks:
    - name: Display Linux Distribution
      debug:
        msg: "Server {{ inventory_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})."

    - name: Log OS Distribution and Version (Before Patching)
      set_fact:
        os_distribution_before: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
        os_kernel_before: "{{ ansible_kernel }}"
        uptime_seconds_before: "{{ ansible_uptime_seconds }}"
        current_datetime: "{{ ansible_date_time.iso8601_basic }}"

    - name: Check for updates on Red Hat-based systems (e.g., CentOS, RHEL, Rocky Linux)
      yum:
        update_cache: true
      register: yum_update_result
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

    - name: Set fact for available updates
      set_fact:
        updates_available: "{{ yum_update_result.changed }}"

    - name: Count and list available updates
      debug:
        msg:
          - "Updates available: {{ updates_available }}"
          - "Packages to be updated:"
          - "{{ check_updates_result.updates | default([]) }}"
      # when: updates_available

    - name: Apply updates on Red Hat-based systems if any are available
      package:
        name: "*"
        state: latest
      register: install_updates_result
      when: updates_available

    - name: Check if a restart is needed on Red Hat-based systems
      command: needs-restarting -r
      register: rpm_restart_needed
      failed_when: rpm_restart_needed.rc != 0
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

    - name: Set fact if reboot is required
      set_fact:
        reboot_required: "{{ rpm_restart_needed.changed }}"

    - name: Restart the server if updates require it (Red Hat-based)
      reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 10
      # ignore_errors: true
      register: reboot_result
      when: rpm_restart_needed is changed

    - name: Log OS Distribution and Version (After Patching)
      gather_facts: # Re-gather facts

    - name: Set facts for post-patching information
      set_fact:
        os_distribution_after: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
        os_kernel_after: "{{ ansible_kernel }}"
        uptime_seconds_after: "{{ ansible_uptime_seconds }}"

    - name: Generate HTML Report
      template:
        src: report.html.j2
        dest: "{{ report_file }}"

    - name: Notify user about restarts that were scheduled
      debug:
        msg: "Server {{ inventory_hostname }} has been restarted."
      when: rpm_restart_needed is changed
